{ inputs, ... }:
{
  flake-file.inputs.git-hooks = {
    url = "github:cachix/git-hooks.nix";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  imports = [ inputs.git-hooks.flakeModule ];

  perSystem =
    { pkgs, ... }:
    {
      # Runs inside `nix flake check` and as `.#checks.<system>.pre-commit`, so
      # CI and local `just lint` / `pre-commit run` share one pinned toolchain.
      pre-commit.settings.hooks = {
        # flake.nix is generated by flake-file, hence the exclusions here and
        # in deadnix.
        statix = {
          enable = true;
          settings = {
            ignore = [ "flake.nix" ];
            config = ".statix.toml";
          };
        };

        # Lambda-arg checks must stay off: this repo is almost entirely
        # `{ config, lib, pkgs, ... }` module functions.
        deadnix = {
          enable = true;
          excludes = [ "flake\\.nix" ];
          settings = {
            noLambdaPatternNames = true;
            noLambdaArg = true;
          };
        };

        actionlint.enable = true;

        # Enforce .editorconfig across all file types, not just *.nix.
        editorconfig-checker = {
          enable = true;
          excludes = [
            "flake\\.lock"
            "^result"
          ];
        };

        # Spell check; all config (excludes, word allowlist) lives in _typos.toml.
        typos.enable = true;

        # GitHub Actions security static analysis; --offline because there is
        # no token to query the API with.
        zizmor = {
          enable = true;
          name = "zizmor";
          entry = "${pkgs.zizmor}/bin/zizmor --offline";
          files = "^\\.github/workflows/.*\\.ya?ml$";
          pass_filenames = true;
        };
      };
    };
}
